_wandb:
    value:
        cli_version: 0.23.0
        e:
            czl9tbbp3feofogfw8o15nw551b4p7nh:
                codePath: /workspace/01_data-extractor/src/mop/mop_napzack.py
                codePathLocal: mop_napzack.py
                cpu_count: 32
                cpu_count_logical: 64
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "982240026624"
                        used: "89127833600"
                email: benzelongji@gmail.com
                executable: /opt/testenv/bin/python
                git:
                    commit: 435eff8866ec70f61028ad0cf2f94e09fedc7b0f
                    remote: https://github.com/Honzawa-Ryu/data-extractor.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-02050c4c-2f83-122f-ca55-d76516bd5d83
                host: 52de807de9b1
                memory:
                    total: "134921465856"
                os: Linux-6.14.0-36-generic-x86_64-with-glibc2.35
                program: /workspace/01_data-extractor/src/mop/mop_napzack.py
                python: CPython 3.11.9
                root: /workspace/01_data-extractor/src/mop
                startedAt: "2025-12-23T09:58:43.820162Z"
                writerId: czl9tbbp3feofogfw8o15nw551b4p7nh
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 105
            "2":
                - 105
            "3":
                - 2
                - 13
            "4": 3.11.9
            "5": 0.23.0
            "8":
                - 1
            "12": 0.23.0
            "13": linux-x86_64
